//const server = "https://server.subdomainanimeworld.aniplus.a2hosted.com";
// async function getFiveAnime(file) {
//     let myObject = await fetch(file);
//     fiveAnime = await myObject.json();
//     return fiveAnime
//   }
// getFiveAnime(server + "/anime/animesMainPage/" + 0);

const data = [
    {
        "animeId": 831,
        "englishName": "Boku no Hero Academia 7th Season",
        "hebrewName": "אקדמיית הגיבורים שלי עונה 7",
        "description": "אקדמיית הגיבורים שלי עונה 7",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/fqMHdYPxl3Y?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-05-04T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706553589445Boku no Hero Academia 7th Season.jpg",
        "supernaturl": 1,
        "backgroundImage": null,
        "anotherName": "My Hero Academia Season 7"
    },
    {
        "animeId": 970,
        "englishName": "Code Geass: Dakkan no Rozé",
        "hebrewName": "קוד גיאס: עלייתו של רוז",
        "description": "יעודכן בהמשך",
        "episode": 4,
        "epTime": 57,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/y58cbQpLi0g?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-05-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 1,
        "sliceOfLife": 1,
        "mystery": 1,
        "animeImage": "1708800494552Code Geass: Dakkan no RozÃ©.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 978,
        "englishName": "Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e ",
        "hebrewName": "החריג באקדמיית מלך השדים עונה 2 חלק 2",
        "description": "חלק 2 של \"החריג באקדמיית מלך השדים עונה 2\"",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/Suk6N56VDMQ?si=tN0H90S_Y_WS8qmv",
        "finishedAnime": null,
        "date": "2024-04-12T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1709122070996141651l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Misfit of Demon King Academy II Part 2"
    },
    {
        "animeId": 971,
        "englishName": "The New Gate",
        "hebrewName": "השער החדש",
        "description": "\"השער החדש\", משחק של חיים ומוות בעל עשרות אלפי שחקנים.\nתודות לשין, שחקן ותיק עם יכולות מדהימות, השחקנים האחרים הצליחו להשתחרר מהמשחק.\nלאחר ששין הביס את הבוס האחרון - הוא חשב שהוא יוכל לחזור לעולמו, אך הוא הוכה בפתאומיות באור חזק ומסנוור.\nכאשר הוא התעורר הוא מצא את עצמו בעולם המשחק כ-500 שנים קדימה!\nכך מתחיל לו פרק חדש בחייו של השחקן האגדי!",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/VjeuqBstvdA?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-02T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1708802418196The New Gate.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "THE NEW GATE"
    },
    {
        "animeId": 972,
        "englishName": "Touken Ranbu Kai: Kyoden Moyuru Honnouji",
        "hebrewName": "טוקן ראנבו קאי: כתב קודש - הוננוג'י הבוער",
        "description": "חידוש לאנימה הפורסמת",
        "episode": 8,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/yhWTqEku_KE?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-02T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 1,
        "mystery": 1,
        "animeImage": "1708802536666Touken Ranbu Kai: Kyoden Moyuru Honnouji.jpg",
        "supernaturl": 1,
        "backgroundImage": null,
        "anotherName": "Katsugeki Touken Ranbu"
    },
    {
        "animeId": 832,
        "englishName": "Tokidoki Bosotto Russia-go de Dereru Tonari no Aalya-san",
        "hebrewName": "אליה לפעמים מסתירה את רגשותיה ברוסית",
        "description": "חכמה, עדינה ומדהימה בצורה מופלאה, אליסה מיכאילובנה קוג'ו שהיא גם חצי רוסיה וחצי יפנית נחשבת לאלילה בבית הספר שלה.\nעם שיערה הכסוף, עיניה הכוחות ועורה הבהיר, היא כבשה את לבבם של אינספור תלמידים. למרות זאת, בשל דמותה שנראית בלתי נגישה, כולם סביבה נשארים כזרים.\n\nאחד היוצאים מן הכלל הוא חבר לספסל הלימודים של אליסה, מאסאצ'יקה קוזה, ילד ממוצע שמבלה את חייו בצפייה באנימה ובמשחקי גאצ'ה.\nלמרות האופי שלו, מאסאצ'יקה הוא התלמיד היחיד שקיבל את תשומת ליבה של אליסה.\nללא יכולת להיות כנה, אליסה לפעמים מתנהגת כלפיו בחומרה ומפגינה את חיבתה רק ברוסית.\nעם זאת, אין לה מושג שמאסאצ'יקה באמת מבין את השפה שלה - תוך כדי כך שהוא מעמיד פנים שלא.\n\nככל שהזוג המוזר הזה ממשיך להחליף הערות שנונות ושובבות, מערכת היחסים שלהם הופכת בהדרגה לרומנטית - ואולי סוף סוף אליסה עשויה ללמוד איך להביע את רגשותיה בחופשיות.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/q0UgAfhxKf8?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 1,
        "mystery": 0,
        "animeImage": "1706554015403Tokidoki Bosotto Russia-go de Dereru Tonari no Aalya-san.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Alya Sometimes Hides Her Feelings in Russian"
    },
    {
        "animeId": 833,
        "englishName": "Unnamed Memory",
        "hebrewName": "זיכרון ללא שם",
        "description": "\"המשאלה שלי כאלוף היא שתרדי מהמגדל ותהפכי לאשתי\".\nבטיפוס על מגדל מוות, אוסקר מחפש את כוחה של המאסטר שלו, מכשפת הירח התכול.\nהוא מקווה שהקסם שלה ישבור את הקללה שהורגת כל בחורה שהוא לוקח לאישה.\nכאשר הוא נשבע ביופיה, עולה במוחו רעיון טוב יותר - מכיוון שהמאסטר שלו מספיק חזקה, היא בוודאי תוכל לשרוד את הקללה - והוא צריך להינשא לה במקום!\nטינשה לא מתלהבת מהרעיון, אבל כן מסכימה לחיות עם אוסקר בטירה המלכותית למשך שנה אחת תוך כדי שהיא חוקרת את הקללה שהוטלה על הנסיך.\nפניה היפות של המכשפה מסתירות תקופות וסודות אפלים מחייה.\nעם זאת, ככל שחולף הזמן - הסודות מתחילים לצוף מחדש.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/YU0ew48YlHg?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706554303429Unnamed Memory.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "זכרון ללא שם"
    },
    {
        "animeId": 829,
        "englishName": "Kuroshitsuji: Kishuku Gakkou-hen",
        "hebrewName": "המשרת השחור: מהדורת בית הספר הציבורי",
        "description": "עונה חדשה ל\"משרת השחור\"",
        "episode": 24,
        "epTime": 12,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/Nm3tTTrMovs?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 1,
        "animeImage": "1709830879611141820l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Black Butler: Public School Edition"
    },
    {
        "animeId": 836,
        "englishName": "Mahouka Koukou no Rettousei 3rd Season",
        "hebrewName": "החריג בתיכון הקסם עונה 3",
        "description": "החריג בתיכון הקסם עונה 3",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/18N_vi1IS1s?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706556225732Mahouka Koukou no Rettousei 3rd Season.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Irregular at Magic High School Season 3"
    },
    {
        "animeId": 974,
        "englishName": "Ookami to Koushinryou: Merchant Meets the Wise Wolf",
        "hebrewName": "זאב ותבלין הסוחר מכיר את הזאבה החכמה",
        "description": "הולו היא זאבה אלוהית רבת עוצמה הנערצת בכפר קטן בשם \"פאסלו\" על שבירכה את קציר החיטה השנתי שלהם. למרות זאת ככל שחולפות השנים ותושבי הכפר הופכים להיות עצמאיים יותר, הולו נהפכה לסיפור עם בלבד. כאשר סוחר נודד בשם קראפט לורנס עוצר בכפר, הולו מציעה להפוך לשותפה העסקית שלו אם ייקח אותה לביתה בצפון, יואיץ. הסוחר החכם מזהה את היכולת יוצאת הדופן של הולו להעריך את אופי האנשים ומקבל את הצעתה.\n\nכעת ברשותם כישורי מיקוח חדים ומנהלת משא ומתן כריזמטית, לורנס מתקרב עוד יותר למטרה שלו לפתוח חנות משלו. עם זאת, כאשר לורנס מטייל בכפרים עם הולו בחיפוש אחר הזדמנויות כלכליות, הוא מתחיל להבין שהשאיפות שלו הופכות לאט לאט למשהו בלתי צפוי.\n",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/87qP9hwrSAs?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1709077041364Ookami to Koushinryou: Merchant Meets the Wise Wolf.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Spice and Wolf: Merchant Meets the Wise Wolf"
    },
    {
        "animeId": 839,
        "englishName": "Kimetsu no Yaiba: Hashira Geiko-hen",
        "hebrewName": "קוטל השדים: ארק אימוני אשירה",
        "description": "קוטל השדים עונה 4",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/Sf4cKpeyAbo?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1710010707980141893l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "קוטל השדים עונה 4"
    },
    {
        "animeId": 842,
        "englishName": "Re:Monster",
        "hebrewName": "רי: מונסטר",
        "description": "טומוקאי קנאטה התגלגל מחדש כגובלין החלש ביותר, בשם גובורו, לאחר שעבר מוות מצער.\nעם זאת, זיכרונתיו של גובורו מחייו הקודמים נשמרו.\n",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/NExHn8m88QY?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1709903245363141680l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "בחזרה: מפלצת"
    },
    {
        "animeId": 830,
        "englishName": "Kaijuu 8-gou",
        "hebrewName": "קאיג'ו נו-8",
        "description": "מפלצות גרוטסקיות דמויות גודיזלה הנקראות \"קאיג'ו\" מופיעות ביפן במשך שנים רבות. כדי להילחם באותם המפלצות, יחידה צבאית מובחרת הידועה בשם \"חיל ההגנה\", מסכנת את חייה מידי יום על מנת להגן על האזרחים. ברגע שמפלצת נהרגת, אלו שמכונים בשם \"מטאטאים\" שעובדים תחת אירגון מקצועי למלחמה ב\"קאיג'ו\", דואגים להיפטר מאותם השרידים של המפלצת.\n\nקפקא היבינו, גבר בן 32, אינו מרוצה מתפקידו כמטאטא. מגיל צעיר הוא שאף להצטרף לחיל ההגנה ולחסל קאיג'ואים למחייתו. אולם, לאחר כמה נסיונות כושלים, הוא ויתר על חלומותיו והתפשר על עבודה בינונית אך מספקת משכורת יציבה.\nלמרות זאת, כאשר מתלמד חדש בין 18 בשם לנו איצ'יקאווה מצטרף לצוות המטאטים שלו, קפקא שוב נזכר בחלומותיו להצטרף לצבא.\n \nבעקבות שרשרת אירועים טרגים, קפקא נתקל בקאיג'ו מסוג טפיל, שחודר אליו דרך פיו והופך אותו למפלצת דמוית אדם.\n\nעם כוחותיו החדשים, קפקא שואף לתת ניסיון אחרון להגשמת חלומו.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/c3ljNZsBOxE?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706510616188Kaijuu 8-gou.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Kaiju No. 8"
    },
    {
        "animeId": 840,
        "englishName": "Yozakura-san Chi no Daisakusen",
        "hebrewName": "משימה: משפחת יוזאקורה",
        "description": "תלמיד התיכון טאיו אסאנו נהפך לחסר יכולת חברתית מאז שמשפחתו מתה בתאונת דרכים. האדם היחיד שהצליח לייצר איתו אינטרקציה חברתית, היא חברת הילדות שלו - מוטסומי יוזאקורה, ראש של משפחת המרגלים החזקה בעולם.\nאחיה הבכור של מוטסומי, קיואיצ'ירו יוזאקורה, מגונן עליה יתר על המידה מאז שגרם לה לפציעה קשה.\nאהבתו למוטסומי גדולה, וטאיו הוא המטרה הבאה שלו.\nכדי לשרוד, טאיו חייב להתחתן על מוטסומי ולהיות חבר במשפחת יוזאקורה.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/SBaoM1LUo8M?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706557240331Yozakura-san Chi no Daisakusen.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Mission: Yozakura Family"
    },
    {
        "animeId": 838,
        "englishName": "Wind Breaker",
        "hebrewName": "ווינד ברייקר",
        "description": "הרוקה סאקורה - אינו מתעניין בקשרים עם אנשים חלשים - הוא מעוניין רק בחזקים שבחזקים.\nהוא רק התחיל ללמוד בתיכון פורין, בית ספר שידועים רק בחוזק שלהם - והם משתמשים באותו החוזק על מנת להגן על העיר וכל מי שיחפוץ בכך.\nאבל הרוקה אינו מעוניין להיות גיבור או משהו כזה - הוא רק רוצה להילחם בדרכו עד לפסגה!",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/TlglpoAJZWY?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1709830935897141815l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "וינד ברייקר"
    },
    {
        "animeId": 843,
        "englishName": "Dekisokonai to Yobareta Motoeiyuu wa Jikka kara Tsuihou sareta node Sukikatte ni Ikiru Koto ni Shita",
        "hebrewName": "הגיבור לשעבר שגורש חי כרצונו",
        "description": "ילד בשם אלן לא זכה לקבל את ברכתו של אלן ונקרא כישלון.\nאבל האמת שזהותו האמיתית היא גיבור שהיה חי בעבר - וכוחותיו וזיכרונותיו מחייו הקודמים נשמרו.\nלמרבה המזל בכך שגורש על ידי הדוכס - אלן מנסה להתחיל מסע חדש כבנאדם חופשי. אך לא עובר זמן רב ובוצע בו ניסיון התנקשות על ידי ארוסתו לשעבר?!\n\nזהו הסיפור על הגיבור שגורש שרק רצה להירגע בעולם הזה!",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/ytydzEyvsS0?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706558570425136572l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Banished Former Hero Lives as He Pleases"
    },
    {
        "animeId": 835,
        "englishName": "Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2",
        "hebrewName": "מושוקו טנסיי: גלגול מובטל עונה 2 חלק 2",
        "description": "מושוקו טנסיי: גלגול מובטל עונה 2 חלק 2",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706554839146Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2"
    },
    {
        "animeId": 837,
        "englishName": "Tensei shitara Dainana Ouji Datta node, Kimama ni Majutsu wo Kiwamemasu",
        "hebrewName": "נולדתי מחדש כנסיך השביעי, אז אני יכול לקחת את הזמן ולשפר את יכולות הקסם שלי",
        "description": "הנסיך ליוד לא תמיד היה נסיך... \nלמעשה, בחייו הקודמים - הוא היה קוסם ולנגד עיניו עמדה מטרה אחת - לשלוט ביכולות הקסם שלו באופן מלא.\nבעקבות כך שהוא הוכרח להתגלגל מחדש - הוא ברח להתגלגל כנסיך.\nאך עם חייו החדשים - באו אתגרים חדשים.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/BBWA1Hp_g60?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1709903387820141243l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability"
    },
    {
        "animeId": 841,
        "englishName": "Bartender: Kami no Glass",
        "hebrewName": "ברמן: כוס האל",
        "description": "ברחובות האחוריים של רובע גינזה, מסתתר לו בר בודד בשם \"אולם עדן\", שמופעל על ידי ריו סאסאקורה, ברמן צעיר עם כישרון מופלא, שואמרים שמערבב את הקוקטיילים הכי מדהימים שמישהו אי פעם טעם.\nעם זאת, לא כל אחד יכול למצוא את אולם עדן, אלא אולם עדן מוצא אותך.\nלקוחות מרקעים שונים, כל אחד עם הבעיות שלו, משוטט לבר הזה.\nאף על פי כן, ריו תמיד יודע להכין את הקוקטייל הנכון שיוכל להדריך את הנשמה המבולבלת.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/gIOSNhdJ3zA?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 1,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706557480699Bartender: Kami no Glass.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Bartender: Glass of God"
    },
    {
        "animeId": 834,
        "englishName": "Tensei shitara Slime Datta Ken 3rd Season",
        "hebrewName": "המקרה בו חזרתי לחיים בתור רפש עונה 3",
        "description": "המקרה בו חזרתי לחיים בתור רפש עונה 3",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/U51wKSpONu8?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706554663129Tensei shitara Slime Datta Ken 3rd Season.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "That Time I Got Reincarnated as a Slime Season 3"
    },
    {
        "animeId": 836,
        "englishName": "Mahouka Koukou no Rettousei 3rd Season",
        "hebrewName": "החריג בתיכון הקסם עונה 3",
        "description": "החריג בתיכון הקסם עונה 3",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/18N_vi1IS1s?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706556225732Mahouka Koukou no Rettousei 3rd Season.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Irregular at Magic High School Season 3"
    },
    {
        "animeId": 834,
        "englishName": "Tensei shitara Slime Datta Ken 3rd Season",
        "hebrewName": "המקרה בו חזרתי לחיים בתור רפש עונה 3",
        "description": "המקרה בו חזרתי לחיים בתור רפש עונה 3",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/U51wKSpONu8?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706554663129Tensei shitara Slime Datta Ken 3rd Season.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "That Time I Got Reincarnated as a Slime Season 3"
    },
    {
        "animeId": 838,
        "englishName": "Wind Breaker",
        "hebrewName": "ווינד ברייקר",
        "description": "הרוקה סאקורה - אינו מתעניין בקשרים עם אנשים חלשים - הוא מעוניין רק בחזקים שבחזקים.\nהוא רק התחיל ללמוד בתיכון פורין, בית ספר שידועים רק בחוזק שלהם - והם משתמשים באותו החוזק על מנת להגן על העיר וכל מי שיחפוץ בכך.\nאבל הרוקה אינו מעוניין להיות גיבור או משהו כזה - הוא רק רוצה להילחם בדרכו עד לפסגה!",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/TlglpoAJZWY?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1709830935897141815l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "וינד ברייקר"
    },
    {
        "animeId": 835,
        "englishName": "Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2",
        "hebrewName": "מושוקו טנסיי: גלגול מובטל עונה 2 חלק 2",
        "description": "מושוקו טנסיי: גלגול מובטל עונה 2 חלק 2",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706554839146Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2"
    },
    {
        "animeId": 840,
        "englishName": "Yozakura-san Chi no Daisakusen",
        "hebrewName": "משימה: משפחת יוזאקורה",
        "description": "תלמיד התיכון טאיו אסאנו נהפך לחסר יכולת חברתית מאז שמשפחתו מתה בתאונת דרכים. האדם היחיד שהצליח לייצר איתו אינטרקציה חברתית, היא חברת הילדות שלו - מוטסומי יוזאקורה, ראש של משפחת המרגלים החזקה בעולם.\nאחיה הבכור של מוטסומי, קיואיצ'ירו יוזאקורה, מגונן עליה יתר על המידה מאז שגרם לה לפציעה קשה.\nאהבתו למוטסומי גדולה, וטאיו הוא המטרה הבאה שלו.\nכדי לשרוד, טאיו חייב להתחתן על מוטסומי ולהיות חבר במשפחת יוזאקורה.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/SBaoM1LUo8M?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706557240331Yozakura-san Chi no Daisakusen.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Mission: Yozakura Family"
    },
    {
        "animeId": 843,
        "englishName": "Dekisokonai to Yobareta Motoeiyuu wa Jikka kara Tsuihou sareta node Sukikatte ni Ikiru Koto ni Shita",
        "hebrewName": "הגיבור לשעבר שגורש חי כרצונו",
        "description": "ילד בשם אלן לא זכה לקבל את ברכתו של אלן ונקרא כישלון.\nאבל האמת שזהותו האמיתית היא גיבור שהיה חי בעבר - וכוחותיו וזיכרונותיו מחייו הקודמים נשמרו.\nלמרבה המזל בכך שגורש על ידי הדוכס - אלן מנסה להתחיל מסע חדש כבנאדם חופשי. אך לא עובר זמן רב ובוצע בו ניסיון התנקשות על ידי ארוסתו לשעבר?!\n\nזהו הסיפור על הגיבור שגורש שרק רצה להירגע בעולם הזה!",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/ytydzEyvsS0?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706558570425136572l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Banished Former Hero Lives as He Pleases"
    },
    {
        "animeId": 832,
        "englishName": "Tokidoki Bosotto Russia-go de Dereru Tonari no Aalya-san",
        "hebrewName": "אליה לפעמים מסתירה את רגשותיה ברוסית",
        "description": "חכמה, עדינה ומדהימה בצורה מופלאה, אליסה מיכאילובנה קוג'ו שהיא גם חצי רוסיה וחצי יפנית נחשבת לאלילה בבית הספר שלה.\nעם שיערה הכסוף, עיניה הכוחות ועורה הבהיר, היא כבשה את לבבם של אינספור תלמידים. למרות זאת, בשל דמותה שנראית בלתי נגישה, כולם סביבה נשארים כזרים.\n\nאחד היוצאים מן הכלל הוא חבר לספסל הלימודים של אליסה, מאסאצ'יקה קוזה, ילד ממוצע שמבלה את חייו בצפייה באנימה ובמשחקי גאצ'ה.\nלמרות האופי שלו, מאסאצ'יקה הוא התלמיד היחיד שקיבל את תשומת ליבה של אליסה.\nללא יכולת להיות כנה, אליסה לפעמים מתנהגת כלפיו בחומרה ומפגינה את חיבתה רק ברוסית.\nעם זאת, אין לה מושג שמאסאצ'יקה באמת מבין את השפה שלה - תוך כדי כך שהוא מעמיד פנים שלא.\n\nככל שהזוג המוזר הזה ממשיך להחליף הערות שנונות ושובבות, מערכת היחסים שלהם הופכת בהדרגה לרומנטית - ואולי סוף סוף אליסה עשויה ללמוד איך להביע את רגשותיה בחופשיות.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/q0UgAfhxKf8?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 1,
        "mystery": 0,
        "animeImage": "1706554015403Tokidoki Bosotto Russia-go de Dereru Tonari no Aalya-san.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Alya Sometimes Hides Her Feelings in Russian"
    },
    {
        "animeId": 837,
        "englishName": "Tensei shitara Dainana Ouji Datta node, Kimama ni Majutsu wo Kiwamemasu",
        "hebrewName": "נולדתי מחדש כנסיך השביעי, אז אני יכול לקחת את הזמן ולשפר את יכולות הקסם שלי",
        "description": "הנסיך ליוד לא תמיד היה נסיך... \nלמעשה, בחייו הקודמים - הוא היה קוסם ולנגד עיניו עמדה מטרה אחת - לשלוט ביכולות הקסם שלו באופן מלא.\nבעקבות כך שהוא הוכרח להתגלגל מחדש - הוא ברח להתגלגל כנסיך.\nאך עם חייו החדשים - באו אתגרים חדשים.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/BBWA1Hp_g60?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1709903387820141243l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability"
    },
    {
        "animeId": 839,
        "englishName": "Kimetsu no Yaiba: Hashira Geiko-hen",
        "hebrewName": "קוטל השדים: ארק אימוני אשירה",
        "description": "קוטל השדים עונה 4",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/Sf4cKpeyAbo?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1710010707980141893l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "קוטל השדים עונה 4"
    },
    {
        "animeId": 842,
        "englishName": "Re:Monster",
        "hebrewName": "רי: מונסטר",
        "description": "טומוקאי קנאטה התגלגל מחדש כגובלין החלש ביותר, בשם גובורו, לאחר שעבר מוות מצער.\nעם זאת, זיכרונתיו של גובורו מחייו הקודמים נשמרו.\n",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/NExHn8m88QY?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1709903245363141680l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "בחזרה: מפלצת"
    },
    {
        "animeId": 833,
        "englishName": "Unnamed Memory",
        "hebrewName": "זיכרון ללא שם",
        "description": "\"המשאלה שלי כאלוף היא שתרדי מהמגדל ותהפכי לאשתי\".\nבטיפוס על מגדל מוות, אוסקר מחפש את כוחה של המאסטר שלו, מכשפת הירח התכול.\nהוא מקווה שהקסם שלה ישבור את הקללה שהורגת כל בחורה שהוא לוקח לאישה.\nכאשר הוא נשבע ביופיה, עולה במוחו רעיון טוב יותר - מכיוון שהמאסטר שלו מספיק חזקה, היא בוודאי תוכל לשרוד את הקללה - והוא צריך להינשא לה במקום!\nטינשה לא מתלהבת מהרעיון, אבל כן מסכימה לחיות עם אוסקר בטירה המלכותית למשך שנה אחת תוך כדי שהיא חוקרת את הקללה שהוטלה על הנסיך.\nפניה היפות של המכשפה מסתירות תקופות וסודות אפלים מחייה.\nעם זאת, ככל שחולף הזמן - הסודות מתחילים לצוף מחדש.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/YU0ew48YlHg?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706554303429Unnamed Memory.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "זכרון ללא שם"
    },
    {
        "animeId": 974,
        "englishName": "Ookami to Koushinryou: Merchant Meets the Wise Wolf",
        "hebrewName": "זאב ותבלין הסוחר מכיר את הזאבה החכמה",
        "description": "הולו היא זאבה אלוהית רבת עוצמה הנערצת בכפר קטן בשם \"פאסלו\" על שבירכה את קציר החיטה השנתי שלהם. למרות זאת ככל שחולפות השנים ותושבי הכפר הופכים להיות עצמאיים יותר, הולו נהפכה לסיפור עם בלבד. כאשר סוחר נודד בשם קראפט לורנס עוצר בכפר, הולו מציעה להפוך לשותפה העסקית שלו אם ייקח אותה לביתה בצפון, יואיץ. הסוחר החכם מזהה את היכולת יוצאת הדופן של הולו להעריך את אופי האנשים ומקבל את הצעתה.\n\nכעת ברשותם כישורי מיקוח חדים ומנהלת משא ומתן כריזמטית, לורנס מתקרב עוד יותר למטרה שלו לפתוח חנות משלו. עם זאת, כאשר לורנס מטייל בכפרים עם הולו בחיפוש אחר הזדמנויות כלכליות, הוא מתחיל להבין שהשאיפות שלו הופכות לאט לאט למשהו בלתי צפוי.\n",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/87qP9hwrSAs?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1709077041364Ookami to Koushinryou: Merchant Meets the Wise Wolf.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Spice and Wolf: Merchant Meets the Wise Wolf"
    },
    {
        "animeId": 830,
        "englishName": "Kaijuu 8-gou",
        "hebrewName": "קאיג'ו נו-8",
        "description": "מפלצות גרוטסקיות דמויות גודיזלה הנקראות \"קאיג'ו\" מופיעות ביפן במשך שנים רבות. כדי להילחם באותם המפלצות, יחידה צבאית מובחרת הידועה בשם \"חיל ההגנה\", מסכנת את חייה מידי יום על מנת להגן על האזרחים. ברגע שמפלצת נהרגת, אלו שמכונים בשם \"מטאטאים\" שעובדים תחת אירגון מקצועי למלחמה ב\"קאיג'ו\", דואגים להיפטר מאותם השרידים של המפלצת.\n\nקפקא היבינו, גבר בן 32, אינו מרוצה מתפקידו כמטאטא. מגיל צעיר הוא שאף להצטרף לחיל ההגנה ולחסל קאיג'ואים למחייתו. אולם, לאחר כמה נסיונות כושלים, הוא ויתר על חלומותיו והתפשר על עבודה בינונית אך מספקת משכורת יציבה.\nלמרות זאת, כאשר מתלמד חדש בין 18 בשם לנו איצ'יקאווה מצטרף לצוות המטאטים שלו, קפקא שוב נזכר בחלומותיו להצטרף לצבא.\n \nבעקבות שרשרת אירועים טרגים, קפקא נתקל בקאיג'ו מסוג טפיל, שחודר אליו דרך פיו והופך אותו למפלצת דמוית אדם.\n\nעם כוחותיו החדשים, קפקא שואף לתת ניסיון אחרון להגשמת חלומו.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/c3ljNZsBOxE?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706510616188Kaijuu 8-gou.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Kaiju No. 8"
    },
    {
        "animeId": 829,
        "englishName": "Kuroshitsuji: Kishuku Gakkou-hen",
        "hebrewName": "המשרת השחור: מהדורת בית הספר הציבורי",
        "description": "עונה חדשה ל\"משרת השחור\"",
        "episode": 24,
        "epTime": 12,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/Nm3tTTrMovs?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 1,
        "animeImage": "1709830879611141820l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Black Butler: Public School Edition"
    },
    {
        "animeId": 973,
        "englishName": "Ore dake Level Up na Ken: How to Get Stronger",
        "hebrewName": "עולה רמות לבדי - ריקאפ",
        "description": "פרק ריקאפ המסביר על התרחשויות הסדרה בין פרקים 1 עד 7",
        "episode": 1,
        "epTime": 23,
        "age": "12",
        "trailer": "",
        "finishedAnime": null,
        "date": "2024-02-25T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1708974349874Ore dake Level Up na Ken: How to Get Stronger.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Solo Leveling: How to Get Stronger"
    },
    {
        "animeId": 962,
        "englishName": "Anime&MangaIL",
        "hebrewName": "אנימה&מנגה",
        "description": "ערוץ עדכוני אנימה ומנגה בישראל",
        "episode": 9999,
        "epTime": 9999,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/khhF0aBxDOc?si=MZcD8BxT4oH8fFl0",
        "finishedAnime": null,
        "date": "2024-02-12T07:00:00.000Z",
        "action": 1,
        "comedy": 1,
        "horror": 1,
        "sports": 1,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 1,
        "sliceOfLife": 1,
        "mystery": 1,
        "animeImage": "1707732320739ff0ac65f0b27bbf6.png",
        "supernaturl": 1,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 963,
        "englishName": "Ninja Kamui",
        "hebrewName": "נינג'ה קאמוי",
        "description": "ג'ו היגאן, נינג'ה לשעבר, נמלט מהשבט שלו ומסתתר עם משפחתו באמריקה הכפרית. לילה אחד, צוות מתנקשים מהשבט מוצא אותו וטובח במשפחתו כנקמה על בגידתו. ג'ו, קם לתחייה כנינג'ה קאמי, ומוכן לנקום.\n\nבעולם של המאה ה-21, קאמי הוא אנכרוניזם - נינג'ה עתיק המתמודד מול אויבים חמושים בנשק הייטק. הוא נאבק במתנקשים מאומנים, קרב סייבורגים ונינג'ות יריבות, נחוש להפיל את השבט שגרם לו כל כך הרבה סבל.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/Sjs6MkX9ASU?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-02-11T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 1,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 1,
        "sliceOfLife": 0,
        "mystery": 1,
        "animeImage": "1707813765850Screenshot_62.png",
        "supernaturl": 1,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 825,
        "englishName": "Monsters: Ippyaku Sanjou Hiryuu Jigoku",
        "hebrewName": "מפלצות",
        "description": "יעודכן בהמשך",
        "episode": 1,
        "epTime": 25,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/_NKRzi7kh6Y?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-22T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706046222711137304l.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Monsters: 103 Mercies Dragon Damnation"
    },
    {
        "animeId": 820,
        "englishName": "Bucchigiri?!",
        "hebrewName": "באצ'יגירי",
        "description": "ארג'ין טומושיבי נקלע לקרבות בין אנשים רבי עוצמה לאחר שהתאחד עם חברו לשעבר מטאקרה אסאמין. בינתיים מופיע צל של שד אדיר...?!",
        "episode": 0,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/3lz1HWsNF-I?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-13T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1705346274733139871l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 813,
        "englishName": "Sengoku Youko",
        "hebrewName": "סנגוקו יוקו",
        "description": "העולם מחולק לשני פלגים: בני האדם ומפלצות הנקראות קאטאוורה.\nלמרות היותה קאטאוורה, טאמה אוהבת בני אדם ונשבעה להגן עליהם מפני הרוע - גם אם המשמעות היא להילחם נגד בני מינה.\nאחיה ג'ינקה לעומת זאת, שונא את בני האדם.\nאל האחים מצטרף סייף פחדן ששמו הוא שינסוקה, שרוצה ללמוד איך להתחזק.",
        "episode": 37,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/rAVO8UwJcv4?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-11T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704911861397Sengoku Youko.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Sengoku Basara: Samurai Kings"
    },
    {
        "animeId": 835,
        "englishName": "Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2",
        "hebrewName": "מושוקו טנסיי: גלגול מובטל עונה 2 חלק 2",
        "description": "מושוקו טנסיי: גלגול מובטל עונה 2 חלק 2",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706554839146Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2"
    },
    {
        "animeId": 836,
        "englishName": "Mahouka Koukou no Rettousei 3rd Season",
        "hebrewName": "החריג בתיכון הקסם עונה 3",
        "description": "החריג בתיכון הקסם עונה 3",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/18N_vi1IS1s?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706556225732Mahouka Koukou no Rettousei 3rd Season.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Irregular at Magic High School Season 3"
    },
    {
        "animeId": 830,
        "englishName": "Kaijuu 8-gou",
        "hebrewName": "קאיג'ו נו-8",
        "description": "מפלצות גרוטסקיות דמויות גודיזלה הנקראות \"קאיג'ו\" מופיעות ביפן במשך שנים רבות. כדי להילחם באותם המפלצות, יחידה צבאית מובחרת הידועה בשם \"חיל ההגנה\", מסכנת את חייה מידי יום על מנת להגן על האזרחים. ברגע שמפלצת נהרגת, אלו שמכונים בשם \"מטאטאים\" שעובדים תחת אירגון מקצועי למלחמה ב\"קאיג'ו\", דואגים להיפטר מאותם השרידים של המפלצת.\n\nקפקא היבינו, גבר בן 32, אינו מרוצה מתפקידו כמטאטא. מגיל צעיר הוא שאף להצטרף לחיל ההגנה ולחסל קאיג'ואים למחייתו. אולם, לאחר כמה נסיונות כושלים, הוא ויתר על חלומותיו והתפשר על עבודה בינונית אך מספקת משכורת יציבה.\nלמרות זאת, כאשר מתלמד חדש בין 18 בשם לנו איצ'יקאווה מצטרף לצוות המטאטים שלו, קפקא שוב נזכר בחלומותיו להצטרף לצבא.\n \nבעקבות שרשרת אירועים טרגים, קפקא נתקל בקאיג'ו מסוג טפיל, שחודר אליו דרך פיו והופך אותו למפלצת דמוית אדם.\n\nעם כוחותיו החדשים, קפקא שואף לתת ניסיון אחרון להגשמת חלומו.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/c3ljNZsBOxE?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706510616188Kaijuu 8-gou.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Kaiju No. 8"
    },
    {
        "animeId": 840,
        "englishName": "Yozakura-san Chi no Daisakusen",
        "hebrewName": "משימה: משפחת יוזאקורה",
        "description": "תלמיד התיכון טאיו אסאנו נהפך לחסר יכולת חברתית מאז שמשפחתו מתה בתאונת דרכים. האדם היחיד שהצליח לייצר איתו אינטרקציה חברתית, היא חברת הילדות שלו - מוטסומי יוזאקורה, ראש של משפחת המרגלים החזקה בעולם.\nאחיה הבכור של מוטסומי, קיואיצ'ירו יוזאקורה, מגונן עליה יתר על המידה מאז שגרם לה לפציעה קשה.\nאהבתו למוטסומי גדולה, וטאיו הוא המטרה הבאה שלו.\nכדי לשרוד, טאיו חייב להתחתן על מוטסומי ולהיות חבר במשפחת יוזאקורה.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/SBaoM1LUo8M?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706557240331Yozakura-san Chi no Daisakusen.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Mission: Yozakura Family"
    },
    {
        "animeId": 829,
        "englishName": "Kuroshitsuji: Kishuku Gakkou-hen",
        "hebrewName": "המשרת השחור: מהדורת בית הספר הציבורי",
        "description": "עונה חדשה ל\"משרת השחור\"",
        "episode": 24,
        "epTime": 12,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/Nm3tTTrMovs?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 1,
        "animeImage": "1709830879611141820l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Black Butler: Public School Edition"
    },
    {
        "animeId": 974,
        "englishName": "Ookami to Koushinryou: Merchant Meets the Wise Wolf",
        "hebrewName": "זאב ותבלין הסוחר מכיר את הזאבה החכמה",
        "description": "הולו היא זאבה אלוהית רבת עוצמה הנערצת בכפר קטן בשם \"פאסלו\" על שבירכה את קציר החיטה השנתי שלהם. למרות זאת ככל שחולפות השנים ותושבי הכפר הופכים להיות עצמאיים יותר, הולו נהפכה לסיפור עם בלבד. כאשר סוחר נודד בשם קראפט לורנס עוצר בכפר, הולו מציעה להפוך לשותפה העסקית שלו אם ייקח אותה לביתה בצפון, יואיץ. הסוחר החכם מזהה את היכולת יוצאת הדופן של הולו להעריך את אופי האנשים ומקבל את הצעתה.\n\nכעת ברשותם כישורי מיקוח חדים ומנהלת משא ומתן כריזמטית, לורנס מתקרב עוד יותר למטרה שלו לפתוח חנות משלו. עם זאת, כאשר לורנס מטייל בכפרים עם הולו בחיפוש אחר הזדמנויות כלכליות, הוא מתחיל להבין שהשאיפות שלו הופכות לאט לאט למשהו בלתי צפוי.\n",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/87qP9hwrSAs?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1709077041364Ookami to Koushinryou: Merchant Meets the Wise Wolf.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Spice and Wolf: Merchant Meets the Wise Wolf"
    },
    {
        "animeId": 841,
        "englishName": "Bartender: Kami no Glass",
        "hebrewName": "ברמן: כוס האל",
        "description": "ברחובות האחוריים של רובע גינזה, מסתתר לו בר בודד בשם \"אולם עדן\", שמופעל על ידי ריו סאסאקורה, ברמן צעיר עם כישרון מופלא, שואמרים שמערבב את הקוקטיילים הכי מדהימים שמישהו אי פעם טעם.\nעם זאת, לא כל אחד יכול למצוא את אולם עדן, אלא אולם עדן מוצא אותך.\nלקוחות מרקעים שונים, כל אחד עם הבעיות שלו, משוטט לבר הזה.\nאף על פי כן, ריו תמיד יודע להכין את הקוקטייל הנכון שיוכל להדריך את הנשמה המבולבלת.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/gIOSNhdJ3zA?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 1,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706557480699Bartender: Kami no Glass.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Bartender: Glass of God"
    },
    {
        "animeId": 842,
        "englishName": "Re:Monster",
        "hebrewName": "רי: מונסטר",
        "description": "טומוקאי קנאטה התגלגל מחדש כגובלין החלש ביותר, בשם גובורו, לאחר שעבר מוות מצער.\nעם זאת, זיכרונתיו של גובורו מחייו הקודמים נשמרו.\n",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/NExHn8m88QY?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1709903245363141680l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "בחזרה: מפלצת"
    },
    {
        "animeId": 843,
        "englishName": "Dekisokonai to Yobareta Motoeiyuu wa Jikka kara Tsuihou sareta node Sukikatte ni Ikiru Koto ni Shita",
        "hebrewName": "הגיבור לשעבר שגורש חי כרצונו",
        "description": "ילד בשם אלן לא זכה לקבל את ברכתו של אלן ונקרא כישלון.\nאבל האמת שזהותו האמיתית היא גיבור שהיה חי בעבר - וכוחותיו וזיכרונותיו מחייו הקודמים נשמרו.\nלמרבה המזל בכך שגורש על ידי הדוכס - אלן מנסה להתחיל מסע חדש כבנאדם חופשי. אך לא עובר זמן רב ובוצע בו ניסיון התנקשות על ידי ארוסתו לשעבר?!\n\nזהו הסיפור על הגיבור שגורש שרק רצה להירגע בעולם הזה!",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/ytydzEyvsS0?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706558570425136572l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Banished Former Hero Lives as He Pleases"
    },
    {
        "animeId": 973,
        "englishName": "Ore dake Level Up na Ken: How to Get Stronger",
        "hebrewName": "עולה רמות לבדי - ריקאפ",
        "description": "פרק ריקאפ המסביר על התרחשויות הסדרה בין פרקים 1 עד 7",
        "episode": 1,
        "epTime": 23,
        "age": "12",
        "trailer": "",
        "finishedAnime": null,
        "date": "2024-02-25T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1708974349874Ore dake Level Up na Ken: How to Get Stronger.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Solo Leveling: How to Get Stronger"
    },
    {
        "animeId": 962,
        "englishName": "Anime&MangaIL",
        "hebrewName": "אנימה&מנגה",
        "description": "ערוץ עדכוני אנימה ומנגה בישראל",
        "episode": 9999,
        "epTime": 9999,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/khhF0aBxDOc?si=MZcD8BxT4oH8fFl0",
        "finishedAnime": null,
        "date": "2024-02-12T07:00:00.000Z",
        "action": 1,
        "comedy": 1,
        "horror": 1,
        "sports": 1,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 1,
        "sliceOfLife": 1,
        "mystery": 1,
        "animeImage": "1707732320739ff0ac65f0b27bbf6.png",
        "supernaturl": 1,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 963,
        "englishName": "Ninja Kamui",
        "hebrewName": "נינג'ה קאמוי",
        "description": "ג'ו היגאן, נינג'ה לשעבר, נמלט מהשבט שלו ומסתתר עם משפחתו באמריקה הכפרית. לילה אחד, צוות מתנקשים מהשבט מוצא אותו וטובח במשפחתו כנקמה על בגידתו. ג'ו, קם לתחייה כנינג'ה קאמי, ומוכן לנקום.\n\nבעולם של המאה ה-21, קאמי הוא אנכרוניזם - נינג'ה עתיק המתמודד מול אויבים חמושים בנשק הייטק. הוא נאבק במתנקשים מאומנים, קרב סייבורגים ונינג'ות יריבות, נחוש להפיל את השבט שגרם לו כל כך הרבה סבל.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/Sjs6MkX9ASU?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-02-11T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 1,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 1,
        "sliceOfLife": 0,
        "mystery": 1,
        "animeImage": "1707813765850Screenshot_62.png",
        "supernaturl": 1,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 825,
        "englishName": "Monsters: Ippyaku Sanjou Hiryuu Jigoku",
        "hebrewName": "מפלצות",
        "description": "יעודכן בהמשך",
        "episode": 1,
        "epTime": 25,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/_NKRzi7kh6Y?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-22T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706046222711137304l.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Monsters: 103 Mercies Dragon Damnation"
    },
    {
        "animeId": 820,
        "englishName": "Bucchigiri?!",
        "hebrewName": "באצ'יגירי",
        "description": "ארג'ין טומושיבי נקלע לקרבות בין אנשים רבי עוצמה לאחר שהתאחד עם חברו לשעבר מטאקרה אסאמין. בינתיים מופיע צל של שד אדיר...?!",
        "episode": 0,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/3lz1HWsNF-I?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-13T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1705346274733139871l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 813,
        "englishName": "Sengoku Youko",
        "hebrewName": "סנגוקו יוקו",
        "description": "העולם מחולק לשני פלגים: בני האדם ומפלצות הנקראות קאטאוורה.\nלמרות היותה קאטאוורה, טאמה אוהבת בני אדם ונשבעה להגן עליהם מפני הרוע - גם אם המשמעות היא להילחם נגד בני מינה.\nאחיה ג'ינקה לעומת זאת, שונא את בני האדם.\nאל האחים מצטרף סייף פחדן ששמו הוא שינסוקה, שרוצה ללמוד איך להתחזק.",
        "episode": 37,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/rAVO8UwJcv4?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-11T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704911861397Sengoku Youko.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Sengoku Basara: Samurai Kings"
    },
    {
        "animeId": 816,
        "englishName": "Dosanko Gal wa Namara Menkoi",
        "hebrewName": "הבחורות של הוקאידו סופר חמודות",
        "description": "תלמיד התיכון צובאסה עובר לקיטאמי בעיר בהוקאידו, שם הוא פוגש בחורה בתחנת אוטובוס. המראה שלה עומדת לבדה על רקע נוף השלג הלבן, חשופה ברגליים למרות הקור המקפיא, כובש את לבו. (מקור: MANGA Plus, ערוך)",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/Slv7WZ_4vS8?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-09T07:00:00.000Z",
        "action": 0,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1705001054254Dosanko Gal wa Namara Menkoi.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Hokkaido Gals Are Super Adorable!"
    },
    {
        "animeId": 812,
        "englishName": "Akuyaku Reijou Level 99: Watashi wa Ura-Boss desu ga Maou dewa Arimasen",
        "hebrewName": "נבל רמה 99: אולי אני הבוס הנסתר אבל אני לא אדון השדים",
        "description": "RPG מסויים מתרחש בממלכת וארשיין, שם שיער כהה סופג סטיגמה במידה לא נורמלית. אומיאלה דולקנס היא בתו של רוזן, שנואה מלידה בגלל המנעולים השחורים שלה - והיא גם הבוסית החבויה! בתפנית של גורל, בגיל חמש, אומיאלה נזכרת בזיכרונות מחייה הקודמים ביפן. היא לא מתעניינת בהיבט הרומנטי של המשחק המקורי, היא מתחילה להתמסר לאימון הקסם האפל הנדיר שלה. למרות זאת, המטרות של אומיאלה ברורות: להימנע מלהפוך לבוס הנסתר ולהישאר מחוץ לאור הזרקורים. עם זאת, כשהיא נכנסת לאקדמיה לקסמים, היא מרעידה את היסודות של הממלכה כאשר מעמדה של רמה 99 מתגלה. בין אם מדובר בקטטה פיזית ובין אם מדובר בדו-קרב קסמים, ליכולותיה אין תחרות, ובשילוב עם שיערה השחור, היא בולטת החוצה כמו אגודל כואב. כדי להחמיר את המצב, הגיבורה המקורית מתחילה לחשוד שהיא אדון השדים",
        "episode": 12,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/ODtKada4LM0?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-09T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704886916717Akuyaku Reijou Level 99: Watashi wa Ura-Boss desu ga Maou dewa Arimasen.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Villainess Level 99: I May Be the Hidden Boss but I'm Not the Demon Lord"
    },
    {
        "animeId": 815,
        "englishName": "Tsuki ga Michibiku Isekai Douchuu 2nd Season",
        "hebrewName": "פנטזיה לאור הירח עונה 2",
        "description": "פנטזיה לאור הירח עונה 2",
        "episode": 25,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/qe5D48JdTUc?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-08T07:00:00.000Z",
        "action": 1,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704921315261Tsuki ga Michibiku Isekai Douchuu 2nd Season.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Tsukimichi -Moonlit Fantasy- Season 2"
    },
    {
        "animeId": 811,
        "englishName": "High Card Season 2",
        "hebrewName": "קלף גבוה עונה 2",
        "description": "המשך ישיר לעונה הראשונה",
        "episode": 12,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/bG9NfCYjtfI?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-08T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704836567877High Card Season 2.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 810,
        "englishName": "Nozomanu Fushi no Boukensha",
        "hebrewName": "ההרפתקן שלא מת ואינו רצוי",
        "description": "רנט פאינה, הרפתקן בן 25, פורץ למפלצות כבר עשור. בלי הרבה כישרון לעבודה, רנט מוצא את עצמו תקוע בצייד סליימים וגובלינים תמורת כמויות זעומות של מטבעות בכל יום. הוא עוד לא יודע, כל זה עומד להשתנות כשהוא נתקל בנתיב שלכאורה לא התגלה בצינוק ירח המים.\n\nלעומת זאת, מה שמחכה לו בסוף הדרך הוא לא אוצר ולא עושר, אלא דרקון אגדי שלא מבזבז זמן בלבלוע אותו בשלמותו! הוא מתעורר זמן קצר לאחר מכן, רנט מוצא את עצמו לא ממש מת, אבל גם לא ממש חי - הוא לא יותר מערימה של עצמות! הוא לא חמוש בשום דבר מלבד החרב האמינה שלו, חגורת הכלים והמראה החדש והמגעיל שלו, רנט יוצא למסע שלו כשלד שזה עתה נולד מחדש כדי להשיג אבולוציה קיומית, בתקווה לחזור יום אחד לציוויליזציה עם צורה אנושית יותר.\n\nהאם רנט יצליח, או שהצינוק יאכל אותו לשארית חוסר מותו...?",
        "episode": 12,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/XEaW9p7LXvc?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-08T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704826514636Nozomanu Fushi no Boukensha.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Unwanted Undead Adventurer"
    },
    {
        "animeId": 836,
        "englishName": "Mahouka Koukou no Rettousei 3rd Season",
        "hebrewName": "החריג בתיכון הקסם עונה 3",
        "description": "החריג בתיכון הקסם עונה 3",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/18N_vi1IS1s?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-04-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706556225732Mahouka Koukou no Rettousei 3rd Season.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Irregular at Magic High School Season 3"
    },
    {
        "animeId": 973,
        "englishName": "Ore dake Level Up na Ken: How to Get Stronger",
        "hebrewName": "עולה רמות לבדי - ריקאפ",
        "description": "פרק ריקאפ המסביר על התרחשויות הסדרה בין פרקים 1 עד 7",
        "episode": 1,
        "epTime": 23,
        "age": "12",
        "trailer": "",
        "finishedAnime": null,
        "date": "2024-02-25T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1708974349874Ore dake Level Up na Ken: How to Get Stronger.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Solo Leveling: How to Get Stronger"
    },
    {
        "animeId": 962,
        "englishName": "Anime&MangaIL",
        "hebrewName": "אנימה&מנגה",
        "description": "ערוץ עדכוני אנימה ומנגה בישראל",
        "episode": 9999,
        "epTime": 9999,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/khhF0aBxDOc?si=MZcD8BxT4oH8fFl0",
        "finishedAnime": null,
        "date": "2024-02-12T07:00:00.000Z",
        "action": 1,
        "comedy": 1,
        "horror": 1,
        "sports": 1,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 1,
        "sliceOfLife": 1,
        "mystery": 1,
        "animeImage": "1707732320739ff0ac65f0b27bbf6.png",
        "supernaturl": 1,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 963,
        "englishName": "Ninja Kamui",
        "hebrewName": "נינג'ה קאמוי",
        "description": "ג'ו היגאן, נינג'ה לשעבר, נמלט מהשבט שלו ומסתתר עם משפחתו באמריקה הכפרית. לילה אחד, צוות מתנקשים מהשבט מוצא אותו וטובח במשפחתו כנקמה על בגידתו. ג'ו, קם לתחייה כנינג'ה קאמי, ומוכן לנקום.\n\nבעולם של המאה ה-21, קאמי הוא אנכרוניזם - נינג'ה עתיק המתמודד מול אויבים חמושים בנשק הייטק. הוא נאבק במתנקשים מאומנים, קרב סייבורגים ונינג'ות יריבות, נחוש להפיל את השבט שגרם לו כל כך הרבה סבל.",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/Sjs6MkX9ASU?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-02-11T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 1,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 1,
        "sliceOfLife": 0,
        "mystery": 1,
        "animeImage": "1707813765850Screenshot_62.png",
        "supernaturl": 1,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 825,
        "englishName": "Monsters: Ippyaku Sanjou Hiryuu Jigoku",
        "hebrewName": "מפלצות",
        "description": "יעודכן בהמשך",
        "episode": 1,
        "epTime": 25,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/_NKRzi7kh6Y?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-22T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706046222711137304l.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Monsters: 103 Mercies Dragon Damnation"
    },
    {
        "animeId": 820,
        "englishName": "Bucchigiri?!",
        "hebrewName": "באצ'יגירי",
        "description": "ארג'ין טומושיבי נקלע לקרבות בין אנשים רבי עוצמה לאחר שהתאחד עם חברו לשעבר מטאקרה אסאמין. בינתיים מופיע צל של שד אדיר...?!",
        "episode": 0,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/3lz1HWsNF-I?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-13T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1705346274733139871l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 813,
        "englishName": "Sengoku Youko",
        "hebrewName": "סנגוקו יוקו",
        "description": "העולם מחולק לשני פלגים: בני האדם ומפלצות הנקראות קאטאוורה.\nלמרות היותה קאטאוורה, טאמה אוהבת בני אדם ונשבעה להגן עליהם מפני הרוע - גם אם המשמעות היא להילחם נגד בני מינה.\nאחיה ג'ינקה לעומת זאת, שונא את בני האדם.\nאל האחים מצטרף סייף פחדן ששמו הוא שינסוקה, שרוצה ללמוד איך להתחזק.",
        "episode": 37,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/rAVO8UwJcv4?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-11T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704911861397Sengoku Youko.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Sengoku Basara: Samurai Kings"
    },
    {
        "animeId": 816,
        "englishName": "Dosanko Gal wa Namara Menkoi",
        "hebrewName": "הבחורות של הוקאידו סופר חמודות",
        "description": "תלמיד התיכון צובאסה עובר לקיטאמי בעיר בהוקאידו, שם הוא פוגש בחורה בתחנת אוטובוס. המראה שלה עומדת לבדה על רקע נוף השלג הלבן, חשופה ברגליים למרות הקור המקפיא, כובש את לבו. (מקור: MANGA Plus, ערוך)",
        "episode": 12,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/Slv7WZ_4vS8?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-09T07:00:00.000Z",
        "action": 0,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1705001054254Dosanko Gal wa Namara Menkoi.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Hokkaido Gals Are Super Adorable!"
    },
    {
        "animeId": 812,
        "englishName": "Akuyaku Reijou Level 99: Watashi wa Ura-Boss desu ga Maou dewa Arimasen",
        "hebrewName": "נבל רמה 99: אולי אני הבוס הנסתר אבל אני לא אדון השדים",
        "description": "RPG מסויים מתרחש בממלכת וארשיין, שם שיער כהה סופג סטיגמה במידה לא נורמלית. אומיאלה דולקנס היא בתו של רוזן, שנואה מלידה בגלל המנעולים השחורים שלה - והיא גם הבוסית החבויה! בתפנית של גורל, בגיל חמש, אומיאלה נזכרת בזיכרונות מחייה הקודמים ביפן. היא לא מתעניינת בהיבט הרומנטי של המשחק המקורי, היא מתחילה להתמסר לאימון הקסם האפל הנדיר שלה. למרות זאת, המטרות של אומיאלה ברורות: להימנע מלהפוך לבוס הנסתר ולהישאר מחוץ לאור הזרקורים. עם זאת, כשהיא נכנסת לאקדמיה לקסמים, היא מרעידה את היסודות של הממלכה כאשר מעמדה של רמה 99 מתגלה. בין אם מדובר בקטטה פיזית ובין אם מדובר בדו-קרב קסמים, ליכולותיה אין תחרות, ובשילוב עם שיערה השחור, היא בולטת החוצה כמו אגודל כואב. כדי להחמיר את המצב, הגיבורה המקורית מתחילה לחשוד שהיא אדון השדים",
        "episode": 12,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/ODtKada4LM0?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-09T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 1,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704886916717Akuyaku Reijou Level 99: Watashi wa Ura-Boss desu ga Maou dewa Arimasen.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Villainess Level 99: I May Be the Hidden Boss but I'm Not the Demon Lord"
    },
    {
        "animeId": 810,
        "englishName": "Nozomanu Fushi no Boukensha",
        "hebrewName": "ההרפתקן שלא מת ואינו רצוי",
        "description": "רנט פאינה, הרפתקן בן 25, פורץ למפלצות כבר עשור. בלי הרבה כישרון לעבודה, רנט מוצא את עצמו תקוע בצייד סליימים וגובלינים תמורת כמויות זעומות של מטבעות בכל יום. הוא עוד לא יודע, כל זה עומד להשתנות כשהוא נתקל בנתיב שלכאורה לא התגלה בצינוק ירח המים.\n\nלעומת זאת, מה שמחכה לו בסוף הדרך הוא לא אוצר ולא עושר, אלא דרקון אגדי שלא מבזבז זמן בלבלוע אותו בשלמותו! הוא מתעורר זמן קצר לאחר מכן, רנט מוצא את עצמו לא ממש מת, אבל גם לא ממש חי - הוא לא יותר מערימה של עצמות! הוא לא חמוש בשום דבר מלבד החרב האמינה שלו, חגורת הכלים והמראה החדש והמגעיל שלו, רנט יוצא למסע שלו כשלד שזה עתה נולד מחדש כדי להשיג אבולוציה קיומית, בתקווה לחזור יום אחד לציוויליזציה עם צורה אנושית יותר.\n\nהאם רנט יצליח, או שהצינוק יאכל אותו לשארית חוסר מותו...?",
        "episode": 12,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/XEaW9p7LXvc?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-08T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704826514636Nozomanu Fushi no Boukensha.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Unwanted Undead Adventurer"
    },
    {
        "animeId": 811,
        "englishName": "High Card Season 2",
        "hebrewName": "קלף גבוה עונה 2",
        "description": "המשך ישיר לעונה הראשונה",
        "episode": 12,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/bG9NfCYjtfI?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-08T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704836567877High Card Season 2.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": ""
    },
    {
        "animeId": 815,
        "englishName": "Tsuki ga Michibiku Isekai Douchuu 2nd Season",
        "hebrewName": "פנטזיה לאור הירח עונה 2",
        "description": "פנטזיה לאור הירח עונה 2",
        "episode": 25,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/qe5D48JdTUc?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-08T07:00:00.000Z",
        "action": 1,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704921315261Tsuki ga Michibiku Isekai Douchuu 2nd Season.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Tsukimichi -Moonlit Fantasy- Season 2"
    },
    {
        "animeId": 844,
        "englishName": "Saikyou Tank no Meikyuu Kouryaku: Tairyoku 9999 no Rare Skill-mochi Tank, Yuusha Party wo Tsuihou sa",
        "hebrewName": "פשיטות המבוך של הטנק החזק ביותר עם מיומנות התנגדות נדירה ברמה 9999 ",
        "description": "רוד הוא טנק של קבוצת הגיבורים ויש לו את ההגנה הגבוהה ביותר אי פעם בהיסטוריה. הקבוצה עושה לעתים קרובות פשיטות על מבוך, אבל עבור רוד, זה אומר יותר מסתם פשיטה. כדי לרפא את מחלתה של אחותו האהובה, הוא מחפש את האוצר נותן משאלות שעלול להיות חבוי במבוכים האלה. אבל יום אחד, הגיבור השחצן מעיף אותו מהקבוצה לאחר ניסיון פשיטה לא מוצלח, ומאשים את כישוריו שהוא עדיין לא מודע להשפעותיו. בלי לאן ללכת ואין מה לעשות, הוא מחליט לחזור לעיר הולדתו, שם מחכה אחותו. בדרכו לשם הוא מציל ילדה שהותקפה על ידי מפלצת. באופן בלתי צפוי, לבחורה הזו יש מיומנות נדירה ביותר שנקראת \"הערכה\". הודות למיומנותה, רוד מסוגל לגלות את האמת מאחורי כישוריו הלא ידועים, שמתגלים כישורים חזקים מאוד. עם הגנה של 9999 וכישורים חזקים, כך מתחילה ההרפתקה של הטנק החזק ביותר, רוד!",
        "episode": 12,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/hmo02s4-0wo?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-07T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1706656532347Saikyou Tank no Meikyuu Kouryaku: Tairyoku 9999 no Rare Skill-mochi Tank, Yuusha Party wo Tsuihou sareru.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Strongest Tank's Labyrinth Raids -A Tank with a Rare 9999 Resistance Skill Got Kicked from the Hero's Party-"
    },
    {
        "animeId": 814,
        "englishName": "Mashle: Shinkakusha Kouho Senbatsu Shiken-hen",
        "hebrewName": "מאשל עונה 2",
        "description": "עונה 2 לאנימה מאשל",
        "episode": 12,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/kKPEaart14E?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-06T07:00:00.000Z",
        "action": 1,
        "comedy": 1,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704921243706Mashle: Shinkakusha Kouho Senbatsu Shiken-hen.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Mashle 2nd Season"
    },
    {
        "animeId": 727,
        "englishName": "Kekkon Yubiwa Monogatari",
        "hebrewName": "סיפורי טבעות הנישואין",
        "description": "סאטו מאוהב בחברת ילדותו ושכנתו, הימה, מאז שהיא הופיע משום מקום לפני 10 שנים.\nכעת, יופיה המסנוור אך המסתורי מקשה עליו עוד יותר להתוודת על אהבתו כלפיה.\nהאם כשיום השנה לפגישתם הראשונה מתקרב, הוא יאזור מספיק אומץ כדי להפוך את הידידות שלהם למשהו מעבר לכך?\nאו שמא הוא יחכה למשהו אחר שקשור לזוג הזה?",
        "episode": 12,
        "epTime": 24,
        "age": "18",
        "trailer": "https://www.youtube.com/embed/W61Q5bB4PgE?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-06T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 1,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1700346013522Kekkon Yubiwa Monogatari.jpg",
        "supernaturl": 1,
        "backgroundImage": null,
        "anotherName": "Tales of Wedding Rings"
    },
    {
        "animeId": 806,
        "englishName": "Chiyu Mahou no Machigatta Tsukaikata",
        "hebrewName": "הדרך השגויה להשתמש בקסם ריפוי",
        "description": "קן אוסאטו הוא תלמיד תיכון רגיל בכל מובן המילה - ציונים ממוצעים, חלומות ונטייה לא לאהוב אנשים יוצאי דופן. עם זאת, כאשר הוא נתקל בנשיא ובסגן נשיא מועצת התלמידים, פופולריים ויוצאי דופן, הוא מיד מתיידד איתם. כל זה קורה כאשר חבריו החדשים של קן זומנים לעולם אחר - והוא זומן בטעות גם כן! מדוכדך ובלי שום דרך לחזור, הוא משלים עם להישאר בשקט בעולם החדש - עד שהוא מגלה יש לו זיקה לקסם ריפוי, צורה נדירה מאוד של קסם שנותנת לו גם ביטחון עצמי וגם את תשומת הלב של כל הקוסמים. עם זאת, לא כל תשומת הלב טובה, וזה משהו שקן מבין כשהוא מורגש על ידי בחור מטורף ריפוי משתמש קסום.",
        "episode": 13,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/WMBLLOa3Ldw?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-06T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704628385168Chiyu Mahou no Machigatta Tsukaikata.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "The Wrong Way to Use Healing Magic"
    },
    {
        "animeId": 803,
        "englishName": "Sokushi Cheat ga Saikyou sugite, Isekai no Yatsura ga Marude Aite ni Naranai n desu ga.",
        "hebrewName": "יכולת המוות המיידי שלי כל כך מוגזמת, שאף אחד בעולם האחר הזה לא עומד בפניי!",
        "description": "יוגירי טקאטו מתעורר לכאוס מוחלט בזמן טיול בית הספר, הוא מגלה שכל אחד בכיתה שלו הועבר לעולם אחר! הוא הצליח איכשהו לישון בכל החוויה הקשה הזאת, והחמיץ את המתנה - כוחות שהוענקו לאחרים. על ידי \"החכם\" יצור מסתורי שהופיע כדי להעביר אותם. גרוע מכך, הוא וחבר נוסף לכיתה ננטשו באכזריות על ידי חבריהם, הושארו כפיתיון כדי להסיח את דעתו של דרקון סמוך. למרות שלא נורא מוטרד מהמחשבה למות, הוא מחליט בעל כורחו להגן על הבודד שלו מלווה.",
        "episode": 0,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/gdi9dEqhpQY?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-05T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704554490206Sokushi Cheat ga Saikyou sugite, Isekai no Yatsura ga Marude Aite ni Naranai n desu ga..jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "My Instant Death Ability is So Overpowered, No One in This Other World Stands a Chance Against Me!"
    },
    {
        "animeId": 807,
        "englishName": "Mato Seihei no Slave",
        "hebrewName": "חייל כבול",
        "description": "\"אסון מאטו\". ברחבי יפן, כניסות מסתוריות נפתחו למימד שנקרא \"מאטו\" - מטרופולין שטני מלא במפלצות הרות אסון הידועות בשם \"שווקי\" המאיימות על שלומם של בני האדם. עם זאת, התעוררה תקווה חדשה, כאשר גילוי של פרי מאטו המעניק יכולות על טבעיות אך ורק לנשים אפשר להן להילחם נגד השווקי. בשל כך, הוקמה ממשלה מטריארכלית חדשה, שהקימה ארגון נשים בשם חיל האנטי-שדים, שגרם לגברים ליפול לתחתית החברה.",
        "episode": 12,
        "epTime": 23,
        "age": "18",
        "trailer": "https://www.youtube.com/embed/G8pkEAfILI8?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-04T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704708249648Mato Seihei no Slave.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Chained Soldier"
    },
    {
        "animeId": 804,
        "englishName": "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season",
        "hebrewName": "כיתת העילית עונה 3",
        "description": "עונה 3 לאנימה \"כיתת העילית\"",
        "episode": 13,
        "epTime": 23,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/0yOULRwyp2o?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-03T07:00:00.000Z",
        "action": 0,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 0,
        "drama": 1,
        "fantasy": 0,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1704570569616Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season.jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "Classroom of the Elite III"
    },
    {
        "animeId": 724,
        "englishName": "Solo Leveling",
        "hebrewName": "עולה רמות לבדי",
        "description": "לפני עשר שנים, \"השער\" הופיע וחיבר את העולם האמיתי עם עולם הקסם והמפלצות.\nכדי להילחם בחיות האלו, אנשים מן המניין קיבלו כוחות על וידועים בתור \"ציידים\".\nבחור צעיר בן עשרים ששמו - סונג ג'ין וו הוא אחד מהציידים האלו, אבל הוא ידוע בתור \"הצייד החלש ביותר בעולם\", שאפילו עבור צייד ברמה E הוא נחשב לחלש ביותר.\nעדיין, הוא נילחם במפלצות ברמה הנמוכה ביותר כדי לשלם עבור תרופותיה של אמו.",
        "episode": 24,
        "epTime": 24,
        "age": "12",
        "trailer": "https://www.youtube.com/embed/sqtIagL463A?enablejsapi=1&wmode=opaque&autoplay=1",
        "finishedAnime": null,
        "date": "2024-01-01T07:00:00.000Z",
        "action": 1,
        "comedy": 0,
        "horror": 0,
        "sports": 0,
        "adventure": 1,
        "drama": 0,
        "fantasy": 1,
        "romance": 0,
        "sci_fi": 0,
        "sliceOfLife": 0,
        "mystery": 0,
        "animeImage": "1700345111107138405l[1].jpg",
        "supernaturl": 0,
        "backgroundImage": null,
        "anotherName": "שחקן בודד"
    }
]

export default data;
